python -m torch.distributed.launch --nproc_per_node=1 --master_port=12233 --use_env run_train.py \
--diff_steps 10 \
--lr 0.0001 \
--learning_steps 3 \
--save_interval 10000 \
--seed 102 \
--noise_schedule sqrt \
--hidden_dim 2 \
--bsz 2 \
--dataset qqp \
--data_dir datasets/CommonsenseConversation \
--vocab bert \
--seq_len 128 \
--schedule_sampler lossaware \
--notes test-qqp
